kind: pipeline
type: docker
name: arm64

platform:
  arch: arm64

steps:
- name: test
  image: ubuntu:20.04
  commands:
  - echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
  - apt-get update -qq --yes && apt-get install -qq --yes clang cmake ninja-build python3
  - ./mach build --test -v -c
  - ./mach build --release --test -v -c
 