name: mach_test
description: mach | Test (Debug + Release)
inputs:
  bits:
    description: Bits (`32`, `64`)
    required: true
  edition:
    description: Edition (`c89`, ``)
    required: true
  target:
    description: Target
    required: false
    default: ""
  args:
    description: Any extra arguments
    required: false
    default: ""
runs:
  using: composite
  steps:
    - run: echo "BITS_FLAG=-m32" > $GITHUB_ENV
      shell: bash
      if: ${{ inputs.bits == '32' }}
    - run: echo "BITS_FLAG=" > $GITHUB_ENV
      shell: bash
      if: ${{ inputs.bits == '64' }}

    - run: echo "EDITION_FLAG=-ec89" > $GITHUB_ENV
      shell: bash
      if: ${{ inputs.edition == 'c89' }}
    - run: echo "EDITION_FLAG=" > $GITHUB_ENV
      shell: bash
      if: ${{ inputs.edition == '' }}

    - run: |
        echo "TARGET_FLAG=--target ${{ inputs.target }}" > $GITHUB_ENV
        echo "TEST_COMMAND=--tests" > $GITHUB_ENV
      shell: bash
      if: ${{ inputs.target != '' }}
    - run: echo "TEST_COMMAND=--test" > $GITHUB_ENV
      shell: bash
      if: ${{ inputs.target == '' }}

    - name: mach | Test (Debug + Release)
      shell: bash
      run: |
        ./mach build -v $TEST_COMMAND $BITS_FLAG $EDITION_FLAG $TARGET_FLAG ${{ inputs.args }}
        ./mach build -v $TEST_COMMAND --release $BITS_FLAG $EDITION_FLAG $TARGET_FLAG ${{ inputs.args }}
