name: benchmark_pull_request

on:
  push:
    branches:
      - 'hacl-star-**'
  pull_request:
  workflow_dispatch:
  merge_group:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build
          sudo apt-get install python3 python3-scipy python3-pandas
          sudo apt-get install clang
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          sudo apt-get install libb2-1 

      - name: Checkout hacl-packages (${{ github.ref }})
        uses: actions/checkout@v3
        with:
          path: pr

      - name: Build hacl-packages (${{ github.ref }})
        working-directory: pr
        run: ./mach build --release --benchmarks

      - name: Checkout hacl-packages (main)
        uses: actions/checkout@v3
        with:
          path: main
          ref: main

      - name: Build hacl-packages (main)
        working-directory: main
        run: ./mach build --release --benchmarks

      - name: Run benchmarks
        working-directory: pr
        run: ./mach benchmark --compare ../main
