name: hacl_build

on: [push, pull_request]

jobs:
  # TODO: use composite actions
  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [{cpp: g++-11, c: gcc-11}, {cpp: clang++, c: clang}]
    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cpp }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: brew install ninja
    - name: Debug Build w/ tests
      run: ./mach build --tests -v
    - name: Release Build
      run: ./mach build --release -v
    - name: Install
      run: |
        mkdir pkg-release
        ./mach install -p $PWD/pkg-release -c Release
        mkdir pkg-debug
        ./mach install -p $PWD/pkg-debug
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.compiler.c }}
        path: |
          pkg-debug
          pkg-release
          build/Debug
          build/Release
  build-linux-gcc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc-version: [7, 8, 9, 10, 11]
    env:
      CC: gcc-${{ matrix.gcc-version }}
      CXX: g++-${{ matrix.gcc-version }}
    steps:
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build gcc-${{ matrix.gcc-version }} g++-${{ matrix.gcc-version }}
    - uses: actions/checkout@v2
    - name: Debug Build w/ tests
      run: ./mach build --tests -v
    - name: Release Build
      run: ./mach build --release -v
    - name: Install
      run: |
        mkdir pkg-release
        ./mach install -p $PWD/pkg-release -c Release
        mkdir pkg-debug
        ./mach install -p $PWD/pkg-debug
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-gcc${{ matrix.gcc-version }}
        path: |
          pkg-debug
          pkg-release
          build/Debug
          build/Release
  build-linux-clang:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clang-version: [7, 8, 9, 10]
    env:
      CC: clang-${{ matrix.clang-version }}
      CXX: clang++-${{ matrix.clang-version }}
    steps:
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build clang-${{ matrix.gcc-version }}
    - uses: actions/checkout@v2
    - name: Debug Build w/ tests
      run: ./mach build --tests -v
    - name: Release Build
      run: ./mach build --release -v
    - name: Install
      run: |
        mkdir pkg-release
        ./mach install -p $PWD/pkg-release -c Release
        mkdir pkg-debug
        ./mach install -p $PWD/pkg-debug
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-clang${{ matrix.clang-version }}
        path: |
          pkg-debug
          pkg-release
          build/Debug
          build/Release
