name: gh-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: docs

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@master
      - uses: actions/checkout@master
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - name: Build docs
        run: mdbook build
      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/book
