name: ocaml

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Setup
        id: cache-ocaml-setup
        uses: actions/cache@v3
        with:
          path: ~/.opam
          key: ${{ runner.os }}-ocaml-setup

      - name: Setup
        run: |
          sudo apt-get install ninja-build opam libgmp-dev
          OPAMYES=true opam init --auto-setup --disable-sandboxing --yes --bare
          opam switch create 4.12.0 --yes
          eval $(opam env)
          opam install --yes ocamlfind ctypes zarith cppo

      - name: Debug Build
        run: |
          eval $(opam env)
          ./mach build -l ocaml -v

      - name: Release Build
        run: |
          eval $(opam env)
          ./mach build --release -l ocaml -v

      - name: Test Debug
        run: |
          eval $(opam env)
          ./mach test -l ocaml -v
