name: ocaml

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - CLA.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - cpu-features.md
      - LICENSE
      - LICENSE-APACHE
      - README.md
  pull_request:
    # Can't use an YAML anchor because "Anchors are not currently supported." (GitHub 12/07/2022)
    paths-ignore:
      - .gitignore
      - CLA.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - cpu-features.md
      - LICENSE
      - LICENSE-APACHE
      - README.md
  workflow_dispatch:

jobs:
  # mach:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Cache Setup
  #       id: cache-ocaml-setup
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.opam
  #         key: ${{ runner.os }}-ocaml-setup

  #     - name: System Setup
  #       run: sudo apt-get install ninja-build opam libgmp-dev
  #     - name: OCaml Setup
  #       if: steps.cache-ocaml-setup.outputs.cache-hit != 'true'
  #       run: |
  #         OPAMYES=true opam init --auto-setup --disable-sandboxing --yes --bare
  #         opam switch create 4.12.0 --yes
  #         eval $(opam env)
  #         opam install --yes ocamlfind ctypes zarith cppo

  #     - name: Debug Build
  #       run: |
  #         eval $(opam env)
  #         ./mach build -l ocaml -v

  #     - name: Release Build
  #       run: |
  #         eval $(opam env)
  #         ./mach build --release -l ocaml -v

  #     - name: Test Debug
  #       run: |
  #         eval $(opam env)
  #         ./mach test -l ocaml -v

  packaging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Setup
        id: cache-ocaml-setup
        uses: actions/cache@v3
        with:
          path: ~/.opam
          key: ${{ runner.os }}-ocaml-setup

      - name: System Setup
        run: sudo apt-get install ninja-build opam libgmp-dev
      - name: OCaml Setup
        if: steps.cache-ocaml-setup.outputs.cache-hit != 'true'
        run: |
          OPAMYES=true opam init --auto-setup --disable-sandboxing --yes --bare
          opam switch create 4.12.0 --yes
          eval $(opam env)
          opam install --yes ocamlfind ctypes zarith cppo

      - name: Setup HACL opam
        run: ./opam.sh

      - name: Package & Test
        working-directory: opam
        run: opam install . --verbose --with-test --yes
