name: rust

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - CLA.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - cpu-features.md
      - LICENSE
      - LICENSE-APACHE
      - README.md
  pull_request:
    # Can't use an YAML anchor because "Anchors are not currently supported." (GitHub 12/07/2022)
    paths-ignore:
      - .gitignore
      - CLA.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - cpu-features.md
      - LICENSE
      - LICENSE-APACHE
      - README.md
  workflow_dispatch:

jobs:
  mach:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo

      - if: matrix.os == 'macos-latest'
        run: brew install ninja

      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install ninja-build

      - if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - if: matrix.os == 'windows-latest'
        run: choco install ninja

      - name: Cargo update
        working-directory: rust
        run: cargo update

      - name: Debug Build
        run: ./mach build -l rust -v

      - name: Release Build
        run: ./mach build --release -l rust -v

      - name: Test Debug
        # FIXME: enable Windows tests
        if: matrix.os != 'windows-latest'
        run: cargo test --manifest-path rust/Cargo.toml
        env:
          MACH_BUILD: 1

  standalone:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          # - windows-latest # FIXME

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo

      - if: matrix.os == 'macos-latest'
        run: brew install ninja

      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install ninja-build

      - if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - if: matrix.os == 'windows-latest'
        run: choco install ninja

      - name: Prepare
        run: ./mach rust

      - name: Cargo update
        working-directory: rust
        run: cargo update

      - name: Debug Build
        working-directory: rust
        run: cargo build -v

      - name: Release Build
        working-directory: rust
        run: cargo build --release -v

      - name: Test Debug
        working-directory: rust
        run: cargo test -v
